(require 'window-purpose)
(require 'window-purpose-x)
(purpose-x-magit-multi-on)
(purpose-mode)

(add-to-list 'purpose-user-mode-purposes '(clojure-mode . src))
(add-to-list 'purpose-user-mode-purposes '(emacs-lisp-mode . src))
(add-to-list 'purpose-user-mode-purposes '(cider-repl-mode . clj-repl))
(add-to-list 'purpose-user-mode-purposes '(eshell-mode . shells))
(add-to-list 'purpose-user-mode-purposes '(magit-status-mode . shells))
(purpose-compile-user-configuration)
(provide 'slipset-purpose)
